In [13]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.datasets import load_iris

In [6]:
df = pd.read_csv("IMDb.csv")

In [14]:
df

,Rank,Title,Year,Genre(s),Director,Main Actor(s),Country,IMDb Rating,Votes,Runtime (mins)
0,1,The Shawshank Redemption,1994,Drama,Frank Darabont,Tim Robbins|Morgan Freeman|Bob Gunton,DK|AT,9.3,3219532,142
1,2,The Godfather,1972,Crime|Drama,Francis Ford Coppola,Marlon Brando|Al Pacino|James Caan,DK|AT,9.2,2244476,175
2,3,The Dark Knight,2008,Crime|Thriller,Christopher Nolan,Christian Bale|Heath Ledger|Aaron Eckhart,DK|LV,9.1,3205233,152
3,4,The Lord of the Rings: The Return of the King,2003,Adventure|Drama|Fantasy,Peter Jackson,Elijah Wood|Viggo Mortensen|Ian McKellen,DK|MK,9.0,2181911,201
4,5,Schindler's List,1993,Biography|Drama|History,Steven Spielberg,Liam Neeson|Ralph Fiennes|Ben Kingsley,DK|LV,9.0,1595992,195
...,...,...,...,...,...,...,...,...,...,...
695,696,The Count of Monte Cristo,2002,Action|Adventure|Drama,Kevin Reynolds,Jim Caviezel|Guy Pearce|Christopher Adamson,LV|DK,7.7,161156,131
696,697,The Cove,2009,Biography|Crime|Documentary,Louie Psihoyos,NaN,DK|PT,8.4,52761,92
697,698,The Wages of Fear,1953,Adventure|Drama|Thriller,Henri-Georges Clouzot,Yves Montand|Charles Vanel|Peter van Eyck,DK|AT,8.1,74075,156
698,699,Good Bye Lenin!,2003,Comedy|Drama|Romance,Wolfgang Becker,Daniel Brühl|Katrin Sass|Chulpan Khamatova,PT|ZA,7.7,160485,121
699,700,Nosferatu,1922,Fantasy|Horror,F.W. Murnau,Max Schreck|Alexander Granach|Gustav von Wange...,LV|AT,7.8,123996,95

In [123]:
def impute_missing(data, strategy= "mean", columns=None):
    if strategy=="mean":
        return mean(data, columns)
    elif strategy=="median":
        return median(data,columns)
    elif strategy == "mode":
        return mode(data,columns)
    else:
        print("You've inserted a non valid strategy")

In [126]:
def mean(df, columns=None):
    df_copy=df.copy()
    columnas_numericas = df.select_dtypes(include=['int', 'float']).columns
    if columns is not None:
        cols=[]
        for i in columnas_numericas:
            if i in columns:
                cols.append(i)
        columnas_numericas=cols
    
    for columna in columnas_numericas:
        mean= df_copy[columna].sum()/df_copy[columna].count()
        df_copy[columna]=df_copy[columna].fillna(mean)
    
    return df_copy

In [128]:
def median(df, columns=None):
    df_copy=df.copy()
    columnas_numericas = df.select_dtypes(include=['int', 'float']).columns
    if columns is not None:
        cols=[]
        for i in columnas_numericas:
            if i in columns:
                cols.append(i)
        columnas_numericas=cols
    for columna in columnas_numericas:
        median=df_copy[columna].sort_values().dropna()
        n=len(median)
        if n%2!=0:
            median=median.iloc[n//2]
        else:
            median=(median.iloc[n//2-1]+median.iloc[n//2])/2
        df_copy[columna]=df_copy[columna].fillna(median)
    return df_copy
median(df)

    edad  salario  antiguedad departamento
0  False    False       False       ventas
1  False    False       False       ventas
2  False    False       False          NaN
3  False    False       False           IT
4  False    False       False           IT
5  False    False       False           RH
6  False    False       False       ventas

In [130]:
def mode(df, columns=None):
    df_copy=df.copy()
    columnas=df_copy.columns
    if columns is not None:
        cols=[]
        for i in columnas:
            if i in columns:
                cols.append(i)
        columnas=cols
    for columna in columnas:
        repetidos={}
        for registro in df_copy[columna]:
            if registro in repetidos:
                repetidos[registro]+=1
            else:
                repetidos[registro]=1
        mode=max(repetidos, key=repetidos.get)
        df_copy[columna]=df_copy[columna].fillna(mode)
    return df_copy

mode(df)

    edad  salario  antiguedad departamento
0  False    False       False       ventas
1  False    False       False       ventas
2  False    False       False       ventas
3  False    False       False           IT
4  False    False       False           IT
5  False    False       False           RH
6  False    False       False       ventas

In [171]:
import pandas as pd
import numpy as np

data = {
    'edad': [25, 30, np.nan, 22, 28, 35, np.nan],
    'salario': [15000, 18000, 20000, np.nan, 16000, np.nan, 22000],
    'antiguedad': [1, 3, 2, 5, np.nan, 4, 2],
    'departamento': ['ventas', 'ventas', np.nan, 'IT', 'IT', 'RH', 'ventas']
}

df = pd.DataFrame(data)
print(df)

   edad  salario  antiguedad departamento
0  25.0  15000.0         1.0       ventas
1  30.0  18000.0         3.0       ventas
2   NaN  20000.0         2.0          NaN
3  22.0      NaN         5.0           IT
4  28.0  16000.0         NaN           IT
5  35.0      NaN         4.0           RH
6   NaN  22000.0         2.0       ventas

In [173]:
# Imputar todas las columnas numéricas con la media
print(impute_missing(df, strategy='mean'))

# Imputar todas las columnas numéricas con la mediana
print(impute_missing(df, strategy='median'))

# Imputar todas las columnas (incluida 'departamento') con la moda
print(impute_missing(df, strategy='mode'))

# Imputar solo una columna específica
print(impute_missing(df, strategy='mean', columns=['salario']))

   edad  salario  antiguedad departamento
0  25.0  15000.0    1.000000       ventas
1  30.0  18000.0    3.000000       ventas
2  28.0  20000.0    2.000000          NaN
3  22.0  18200.0    5.000000           IT
4  28.0  16000.0    2.833333           IT
5  35.0  18200.0    4.000000           RH
6  28.0  22000.0    2.000000       ventas
   edad  salario  antiguedad departamento
0  25.0  15000.0         1.0       ventas
1  30.0  18000.0         3.0       ventas
2  28.0  20000.0         2.0          NaN
3  22.0  18000.0         5.0           IT
4  28.0  16000.0         2.5           IT
5  35.0  18000.0         4.0           RH
6  28.0  22000.0         2.0       ventas
   edad  salario  antiguedad departamento
0  25.0  15000.0         1.0       ventas
1  30.0  18000.0         3.0       ventas
2  25.0  20000.0         2.0       ventas
3  22.0  15000.0         5.0           IT
4  28.0  16000.0         2.0           IT
5  35.0  15000.0         4.0           RH
6  25.0  22000.0         2.0       ventas
   edad  salario  antiguedad departamento
0  25.0  15000.0         1.0       ventas
1  30.0  18000.0         3.0       ventas
2   NaN  20000.0         2.0          NaN
3  22.0  18200.0         5.0           IT
4  28.0  16000.0         NaN           IT
5  35.0  18200.0         4.0           RH
6   NaN  22000.0         2.0       ventas

In [236]:
def detect_outliers(data, method='iqr', threshold=1.5):
    if method=="iqr":
        return iqr(df,threshold)
    elif method=="zscore":
        return zscore(df,threshold)
    else:
        print("You've inserted a non valid strategy")

In [238]:
def iqr(df, threshold = 1):
    df_copy = pd.DataFrame(False, index=df.index, columns=df.columns)
    columnas_numericas = df.select_dtypes(include=['int', 'float']).columns
    for columna in columnas_numericas:
        q1=df[columna].quantile(0.25)
        q3=df[columna].quantile(0.75)
        iqr=q3-q1
        limite_sup=q3+threshold*iqr
        limite_inf=q1-threshold*iqr
        outliers=(df[columna]>limite_sup)|(df[columna]<limite_inf)
        df_copy[columna]=outliers
    return df_copy

iqr(df)

    edad  salario  antiguedad  departamento
0  False    False       False         False
1  False    False       False         False
2  False    False       False         False
3  False    False       False         False
4  False    False       False         False
5  False    False       False         False
6  False    False       False         False

In [240]:
def zscore(df, threshold =1.5):
    df_copy = pd.DataFrame(False, index=df.index, columns=df.columns)
    columnas_numericas = df.select_dtypes(include=['int', 'float']).columns
    for columna in columnas_numericas:
        mean=df[columna].sum()/df[columna].count()
        std= df[columna].std(ddof=0)
        zscore=(df[columna]-mean)/std
        df_copy[columna]= zscore.abs()>threshold
    return df_copy

In [246]:
detect_outliers(data, method='iqr', threshold=0)

    edad  salario  antiguedad  departamento
0  False     True        True         False
1  False    False       False         False
2  False    False       False         False
3   True    False        True         False
4  False    False       False         False
5   True    False        True         False
6  False     True       False         False

In [33]:
def handle_outliers(data, method='iqr',action='trim', threshold=1.5):
    df_copy=data.copy()
    columnas_numericas = df_copy.select_dtypes(include=['int', 'float']).columns
    for columna in columnas_numericas:
        if method=="iqr":
            q1=df_copy[columna].quantile(0.25)
            q3=df_copy[columna].quantile(0.75)
            iqr=q3-q1
            limite_sup=q3+threshold*iqr
            limite_inf=q1-threshold*iqr
        elif method=="zscore":
            mean=df_copy[columna].sum()/df_copy[columna].count()
            std= df_copy[columna].std(ddof=0)
            limite_sup= mean+threshold*std
            limite_inf = mean-threshold*std
        else:
            print("You've inserted a non valid strategy")
            return data
            
        if action == "trim":
            df_copy=df_copy[(df_copy[columna] >= limite_inf) & (df_copy[columna]<= limite_sup)]
        elif action =="cap":
            df_copy[columna]=df_copy[columna].clip(lower=limite_inf, upper=limite_sup)
        else:
            print("You've inserted a non valid strategy")
            return data
    return df_copy

In [37]:
handle_outliers(df3, method='zscore', action='trim', threshold=1.5)

   edad  salario
0    25    15000
1    28    16000
3    30    15500
4    27    16200
5    26    15800

In [31]:
import inspect
print(inspect.getsource(handle_outliers))

def handle_outliers(data, method='iqr',action='trim', threshold=1.5):
    df_copy=data.copy()
    columnas_numericas = df_copy.select_dtypes(include=['int', 'float']).columns
    for columna in columnas_numericas:
        if method=="iqr":
            q1=df_copy[columna].quantile(0.25)
            q3=df_copy[columna].quantile(0.75)
            iqr=q3-q1
            limite_sup=q3+threshold*iqr
            limite_inf=q1-threshold*iqr
        elif method=="zscore":
            mean=df_copy[columna].sum()/df_copy[columna].count()
            std= df_copy[columna].std(ddof=0)
            limite_sup= mean+threshold*std
            limite_inf = mean-threshold*std
        else:
            print("You've inserted a non valid strategy")
            return data

        if action == "trim":
            df_copy=df_copy[(df_copy[columna] >= limite_inf) & (df_copy[columna]<= limite_sup)]
        elif action =="cap":
            df_copy[columna]=df_copy[columna].clip(lower=limite_inf, upper=limite_sup)
        else:
            print("You've inserted a non valid strategy")
        return data
    return df_copy